### ISSUE TITLE
Bug Report: [error] Ubuntu 22.04.1 LTS is not supported!

### ISSUE THREAD

**Issue by chaoqunxie** [home-assistant/supervised-installer#271] opened 2023-01-10 06:43 UTC
### OS Version

Ubuntu 22.04.1 LTS

### System Information

Linux ubuntu 5.18.19-051819-generic #202208211443 SMP PREEMPT_DYNAMIC Sun Aug 21 15:10:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What happened?

when exec   'dpkg -i homeassistant-supervised.deb' 

### Machine Type

generic-x86-64

### Installer output

```text
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[error] Ubuntu 22.04.1 LTS is not supported!
dpkg: error processing archive homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
No diversion 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised', none removed.
[info] Resetting debconf selections
[info] Removal complete, due to the complexity of this installation method,
[info] you will need to manually remove the containers created by the supervisor
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Kanga-Who** [comment] 2023-01-10 06:45
Read the ADR - Ubuntu is not supported.

**Comment by chaoqunxie** [comment] 2023-01-10 06:48
> Read the ADR - Ubuntu is not supported, you ticked the tick saying you understood this.

i install successfully  in Ubuntu 20.04.5 LTS

**Comment by Kanga-Who** [comment] 2023-01-10 06:56
```
[error] Ubuntu 22.04.1 LTS is not supported!
```

Read the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) - Debian Linux Debian 11 aka Bullseye (no derivatives)

**Comment by chaoqunxie** [comment] 2023-01-10 07:10
thank u,i understand,Will you support it in the future？

**Comment by LucaArietti** [comment] 2023-01-11 22:17
I have the same problem. And I understand that ubuntu is not supported.
But, in this forum a user said he succeeded in installation on ubuntu 22.04.1

https://community.home-assistant.io/t/ha-supervisor-installation-2022-09-dev1703-on-ubuntu-20-04-5-failed-network-access-missing/462497/5

How is it possible?

**Comment by LucaArietti** [comment] 2023-01-12 00:00
I managed to make it work!
from this page https://github.com/home-assistant/supervised-installer/releases 
I was downloading 1.4.1 instead I tried to download 1.3.1 and got another error:
```
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on docker-ce; however:
  Package docker-ce is not installed.
```
which sounded strange to me, I think it's because when I installed ubuntu server I put the X on docker and it installed it via snap. So now I installed with apt install docker-ce, following this guide
https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

in this way I think I messed up a bit with docker (it's the first time I use docker), maybe I overwritten what I had, because it removed a container I had (pihole). But no matter, homeassistant container remained.
I then tried to install the 1.4.1 version of homeassistant-supervised.deb but it still didn't work. So I stayed with 1.3.1 and it worked! It installed successfully.
It gave me an error that I couldn't ping something, I think it was due to some problem with the pihole I had. Rebooting and fiddling around a bit it went and rebooting again it installed correctly. **After reboot, I waited about half an hour before reconfiguring homeassistant.** The installation of the supervisor took quite a while in fact.

I also followed this guide a bit
https://www.diyenjoying.com/2022/10/01/install-home-assistant-supervisor-onto-ubuntu/

**Comment by Kanga-Who** [comment] 2023-01-12 00:14
All of which was a waste of time, you could have just installed Debian and had a working install in 30mins.

You _will_ have issues with Ubuntu. Good luck fixing them.

**Comment by LucaArietti** [comment] 2023-01-12 00:21
Yes, I simply agree with you. Since home assistant was reporting many critical problems, I decided to format everything and i'm installing debian

**Comment by Kanga-Who** [comment] 2023-01-12 00:23
https://community.home-assistant.io/t/installing-home-assistant-supervised-on-debian-11/200253

**Comment by LucaArietti** [comment] 2023-01-12 01:24
I install debian and followed your valuable guide to the letter (good job!). At the command dpkg -i homeassistant-supervised.deb I was successful:
```
done
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://192.168.1.45:8123
[warn] A reboot is required to apply changes to grub.
```
however, both before and after the operating system restart, doing 'tail -f syslog' gives me this error, and indeed homeassistant is not reachable from the browser:
```
Jan 12 02:15:37 arietsrack hassio_supervisor[606]: #033[31m23-01-12 02:15:37 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-cli:2022.11.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.11.0&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-cli&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on [::1]:53: read udp [::1]:41155->[::1]:53: read: connection refused")#033[0m
Jan 12 02:15:37 arietsrack hassio_supervisor[606]: #033[33m23-01-12 02:15:37 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec#033[0m
Jan 12 02:16:07 arietsrack hassio_supervisor[606]: #033[32m23-01-12 02:16:07 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-cli with tag 2022.11.0.#033[0m
Jan 12 02:16:07 arietsrack dockerd[606]: time="2023-01-12T02:16:07.103417465+01:00" level=warning msg="Error getting v2 registry: Get \"https://ghcr.io/v2/\": dial tcp: lookup ghcr.io on [::1]:53: read udp [::1]:54301->[::1]:53: read: connection refused"
Jan 12 02:16:07 arietsrack dockerd[606]: time="2023-01-12T02:16:07.103454513+01:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://ghcr.io/v2/\": dial tcp: lookup ghcr.io on [::1]:53: read udp [::1]:54301->[::1]:53: read: connection refused"
Jan 12 02:16:07 arietsrack dockerd[606]: time="2023-01-12T02:16:07.109817703+01:00" level=error msg="Handler for POST /v1.41/images/create returned error: Get \"https://ghcr.io/v2/\": dial tcp: lookup ghcr.io on [::1]:53: read udp [::1]:54301->[::1]:53: read: connection refused"
```

could you please help me? I searched in the discussion under the guide but nobody has my error

**Comment by LucaArietti** [comment] 2023-01-12 12:09
I found the solution, as explained here https://community.ui.com/questions/Connection-Refused-Failed-to-pull-docker-images/6f817655-56aa-4c3f-83fc-8ff2afd3ac2c

_We suppose that the cause may be in your DNS settings. Can you please try to run this command:  'docker run hello-world' ?_
In fact, this command gave me the same error.
I had to change my system's DNS. Here's what I did (all in sudo):

```
rm -r /etc/resolv.conf
nano /etc/resolv.conf
```
written in (the Google DNS)
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```
 
Close and save the file. You can do so by clicking Ctrl + X and pressing Y. Continue typing in the terminal:

```
chattr +i /etc/resolv.conf
reboot now
```

After reboot, wait 10 minutes.
Everything works now!

**Comment by frenck** [comment] 2023-01-12 18:00
> OS Version
> Ubuntu 22.04.1 LTS

Closing this issue, as Ubuntu isn't supported.

../Frenck

**Closed by frenck** 2023-01-12 18:00 UTC
Labels: bug
