### ISSUE TITLE
Installation of DEB file indicates docker-ce required

### ISSUE THREAD

**Issue by dcmartin** [home-assistant/supervised-installer#193] opened 2022-02-15 17:41 UTC
I have Jetson AGX-1 and Jetson Nano both with Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3

Running `apt list docker` shows only `docker` and not `docker-ce`

Installation reports error that `docker-ce` is required, but not installed; ONLY on AGX-1

```
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on docker-ce; however:
  Package docker-ce is not installed.

dpkg: error processing package homeassistant-supervised (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 homeassistant-supervised
```
This is using latest (1.10) version of DEB file.

**Comment by dcmartin** [comment] 2022-02-15 18:02
I used --force=all and it then completed successfully; IDK why it's asking for docker-ce.

**Comment by frenck** [comment] 2022-02-15 21:33
The bundles Docker with your Linux distribution is now supported. Please read the requirements as listed for a Supervised installation type.

Closing this issue, as this is not a bug, but actually working as intended.

**Closed by frenck** 2022-02-15 21:33 UTC
