### ISSUE TITLE
Bug Report: Installation error

### ISSUE THREAD

**Issue by Ponyru** [home-assistant/supervised-installer#200] opened 2022-03-21 21:23 UTC
### OS Version

Raspberry pi os 64 bit

### System Information

Raspberry pi 3-4...

### What happened?

Installation error at this stage...

### Machine Type

raspberrypi4-64

### Installer output
```shell
sudo dpkg -i homeassistant-supervised.deb
```

### Relevant log output

```text
ss@raspberrypi:~ $ sudo dpkg -i homeassistant-supervised.deb
Selecting previously unselected package homeassistant-supervised.
(Reading database ... 92442 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
Adding 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Adding 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Adding 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Adding 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.1.0) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
homeassistant-supervised depends on os-agent.

dpkg: error processing package homeassistant-supervised (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
homeassistant-supervised
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by ikifar2012** [comment] 2022-03-23 00:01
Hello @Ponyru, the issue you are facing is not a bug, as I can see you are facing two issues:

1. You must install the [OS Agent](https://github.com/home-assistant/os-agent/tree/main#using-home-assistant-supervised-on-debian) first, as it is a requirement for the installer, without it the install will not start 

2. Raspbian/Raspberry Pi OS is not supported, as per the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) only Debian is supported, therefore I will be closing this issue

Please consider migrating to either the official [Debian Image for Raspberry Pi](https://raspi.debian.net/tested-images/) or [Home Assistant OS](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system)

If you need any help feel free to reach out on [Discord](https://www.home-assistant.io/join-chat/) or the [Home Assistant Community Forums](https://community.home-assistant.io/)

**Closed by ikifar2012** 2022-03-23 00:01 UTC
Labels: bug
