### ISSUE TITLE
Bug Report: supervised not run in debian 12.4.0

### ISSUE THREAD

**Issue by basalisco** [home-assistant/supervised-installer#352] opened 2024-01-20 09:43 UTC
### OS Version

Debian GNU/Linux 12 (bookworm)

### System Information

Linux debian 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

### What happened?

Hello and thank you for your valuable work.

supervisor does not start this log comes from a clean installation on a virtual machine. I have the same problem with my server an x64 system.

P.s. It's not the first time I've installed it. But it seems there is some problem with Debian 12.4.0

### Machine Type

generic-x86-64

### Installer output

```text
root@debian:~# sudo dpkg -i homeassistant-supervised.deb
Selezionato il pacchetto homeassistant-supervised non precedentemente selezionato.
(Lettura del database... 37271 file e directory attualmente installati.)
Preparativi per estrarre homeassistant-supervised.deb...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
[info] Fix kernel dmesg restriction
Viene aggiunto "deviazione di /etc/NetworkManager/NetworkManager.conf in /etc/NetworkManager/NetworkManager.conf.real da homeassistant-supervised"
Viene aggiunto "deviazione di /etc/NetworkManager/system-connections/default in /etc/NetworkManager/system-connections/default.real da homeassistant-supervised"
Viene aggiunto "deviazione di /etc/docker/daemon.json in /etc/docker/daemon.json.real da homeassistant-supervised"
Viene aggiunto "deviazione di /etc/network/interfaces in /etc/network/interfaces.real da homeassistant-supervised"
Estrazione di homeassistant-supervised (1.5.0)...
Configurazione di homeassistant-supervised (1.5.0)...
[info] Restarting NetworkManager
[info] Set up systemd-journal-gatewayd socket file
[info] Enable systemd-journal-gatewayd
[info] Restarting docker service
PING checkonline.home-assistant.io(2606:4700:20::681a:5ee (2606:4700:20::681a:5ee)) 56 data bytes
64 bytes from 2606:4700:20::681a:5ee (2606:4700:20::681a:5ee): icmp_seq=1 ttl=58 time=20.4 ms

--- checkonline.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 20.442/20.442/20.442/0.000 ms
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[info] Switching to cgroup v1
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.1.0-17-amd64
Found initrd image: /boot/initrd.img-6.1.0-17-amd64
Found linux image: /boot/vmlinuz-6.1.0-15-amd64
Found initrd image: /boot/initrd.img-6.1.0-15-amd64
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
done
[info] Within a few minutes you will be able to reach Home Assistant at:
[info] http://homeassistant.local:8123 or using the IP address of your
[info] machine: http://10.0.0.13:8123
[warn] A reboot is required to apply changes to grub.
```

### Relevant log output

```shell
gen 20 10:34:15 debian homeassistant[570]: 2024-01-20 10:34:15.219 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.17.0.2 (172.17.0.2). Requested URL: '/auth/token'. (HomeAssistantSupervisor/2024.01.0.dev1902 aiohttp/3.9.1 Python/3.12)
gen 20 10:34:15 debian hassio_supervisor[570]: 24-01-20 10:34:15 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
gen 20 10:34:20 debian homeassistant[570]: 2024-01-20 10:34:20.233 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.17.0.2 (172.17.0.2). Requested URL: '/auth/token'. (HomeAssistantSupervisor/2024.01.0.dev1902 aiohttp/3.9.1 Python/3.12)
gen 20 10:34:20 debian hassio_supervisor[570]: 24-01-20 10:34:20 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
gen 20 10:34:25 debian homeassistant[570]: 2024-01-20 10:34:25.241 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.17.0.2 (172.17.0.2). Requested URL: '/auth/token'. (HomeAssistantSupervisor/2024.01.0.dev1902 aiohttp/3.9.1 Python/3.12)
gen 20 10:34:25 debian hassio_supervisor[570]: 24-01-20 10:34:25 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
gen 20 10:34:30 debian homeassistant[570]: 2024-01-20 10:34:30.252 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.17.0.2 (172.17.0.2). Requested URL: '/auth/token'. (HomeAssistantSupervisor/2024.01.0.dev1902 aiohttp/3.9.1 Python/3.12)
gen 20 10:34:30 debian hassio_supervisor[570]: 24-01-20 10:34:30 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
gen 20 10:34:33 debian sudo[3170]: basalisco : TTY=pts/0 ; PWD=/home/basalisco ; USER=root ; COMMAND=/usr/bin/journalctl -f
gen 20 10:34:33 debian sudo[3170]: pam_unix(sudo:session): session opened for user root(uid=0) by basalisco(uid=1000)
gen 20 10:34:35 debian homeassistant[570]: 2024-01-20 10:34:35.260 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.17.0.2 (172.17.0.2). Requested URL: '/auth/token'. (HomeAssistantSupervisor/2024.01.0.dev1902 aiohttp/3.9.1 Python/3.12)
gen 20 10:34:35 debian hassio_supervisor[570]: 24-01-20 10:34:35 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by 9runner** [comment] 2024-01-22 10:00
Sounds like this issue is related with docker 24. downgrade to docker 23 may help,

**Comment by NoXPhasma** [comment] 2024-01-22 19:10
I ran into the same issue here on Debian 12, and downgrading to docker 23 was indeed the solution. Thank you, @9runner.

**Comment by derailius** [comment] 2024-01-23 12:40
if it helps, here is what i had to do on debian bookworm.

`sudo apt install -y --allow-downgrades docker-ce=5:24.0.7-1~debian.12~bookworm`

then i had to put a hold on docker-ce with `sudo apt-mark hold docker-ce`

*to remove the hold use: `sudo apt-mark unhold docker-ce`

**Comment by flumiie** [comment] 2024-01-24 05:46
It's honestly frustrating to just having to wait until they fixed this. But I just migrated my entire home assistant supervised setup [into Arch](https://wiki.archlinux.org/title/Home_Assistant_Supervised)

**Comment by agners** [comment] 2024-02-01 15:32
This issue was caused by a bug in upstream Docker 25.0.0. 25.0.1 fixed this problem. I am closing the issue as there is nothing to be done on Supervisor or Supervisor installer side.

Thanks for reporting and help getting to the bottom of this!

**Closed by agners** 2024-02-01 15:32 UTC
Labels: bug
