### ISSUE TITLE
Bug Report: Problems with systemd-resolved in 1.5.0

### ISSUE THREAD

**Issue by ma-ochoa** [home-assistant/supervised-installer#304] opened 2023-06-25 02:36 UTC
### OS Version

Debian 12

### System Information

Linux silver-ha 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### What happened?

Trying to perform a clean installation of HA Supervised, problems occur with the functioning of the systemd-resolved package

In certain scenarios the system runs out of DNS resolution and install fails.

I attach a link that describes the problem (I'm sorry that it's in Spanish, I couldn't find it in English)

https://moss.sh/es/configuracion-problematica-systemd-resolved/

### Machine Type

generic-x86-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by abirvepete** [comment] 2023-06-25 08:43
i got the same problems when i try to use the 1.5.0 to isntall it,systemd-resolved stopped me

**Comment by Dengor1984** [comment] 2023-06-25 11:31
i have the same error:

dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on systemd-resolved; however:
  Package systemd-resolved is not installed.

**Comment by Skrufen** [comment] 2023-06-25 12:33
Getting the same error, unable to get Home Assistant back up and running after a failed upgrade attempt. 
Doesn't look like systemd-resolved is available on Debian 12?

> apt-get install systemd-resolved
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package systemd-resolved is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
> E: Package 'systemd-resolved' has no installation candidate

**Comment by st00m** [comment] 2023-06-25 22:02
The dependency in supervised-installer is wrong.
systemd-resolved is part of package: systemd
At least in my Package: systemd Version: 247.3-7+deb11u2
See: dpkg -L systemd  | grep systemd-resolve

**Comment by rb090** [comment] 2023-06-26 17:14
I have the same issue. I tried to install homeassistant-supervised on Debian 11 with `apt install ./homeassistant-supervised.deb` and this are my logs:

```
root@rpi4-20230102:/tmp# apt install ./homeassistant-supervised.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'homeassistant-supervised' instead of './homeassistant-supervised.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 homeassistant-supervised : Depends: systemd-resolved but it is not installable
E: Unable to correct problems, you have held broken packages.
```

`systemd` is installed on my machine: 

```
root@rpi4-20230102:/tmp# systemd --version
systemd 247 (247.3-7+deb11u2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Comment by rb090** [comment] 2023-06-28 20:37
Thanks a lot @oleksandr-beley 🤝. `dpkg -i --ignore-depends=systemd-resolved homeassistant-supervised.deb` worked for me, I was able to install homeassistant-supervised on Debian 11 👍. But this is just workaround until the  dependency in supervised-installer will be fixed, correct?

**Comment by oleksandr-beley** [comment] 2023-06-29 00:16
Yes, this is just a temporary workaround. I recommend using the second method because using "--ignore-depends" may generate warnings about missing dependencies on the system.

**Comment by ikifar2012** [comment] 2023-06-29 03:14
> The dependency in supervised-installer is wrong. systemd-resolved is part of package: systemd At least in my Package: systemd Version: 247.3-7+deb11u2 See: dpkg -L systemd | grep systemd-resolve

It appears that has changed with Debian 12, I had to install it as a separate dependency on my system. That being said my focus right now is on supporting Debian 12 as the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) states "When a new major version of Debian is released, the previous major version is dropped, with a deprecation time of 4 months."

Not sure if there is an easy way to change the dependency's on a per OS basis without generating multiple packages and considering there is only 4 months until deprecation, I think it makes sense to just stick with the workaround for now as any new installs really should be done on Debian 12 at this point. That being said I am always open to suggestions as long as they comply with the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md)

**Comment by Blogshot** [comment] 2023-07-06 10:54
> > The dependency in supervised-installer is wrong. systemd-resolved is part of package: systemd At least in my Package: systemd Version: 247.3-7+deb11u2 See: dpkg -L systemd | grep systemd-resolve
> 
> It appears that has changed with Debian 12, I had to install it as a separate dependency on my system. That being said my focus right now is on supporting Debian 12 as the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) states "When a new major version of Debian is released, the previous major version is dropped, with a deprecation time of 4 months."
> 
> I could not find easy way to change the dependency's on a per OS basis without generating multiple packages and considering there is only 4 months until deprecation, I think it makes sense to just stick with the workaround for now as any new installs really should be done on Debian 12 at this point. That being said I am always open to suggestions as long as they comply with the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md)

To add on this, here is a part of Bookworm's changelog:
> systemd-resolved has been split into a separate package.
> This new systemd-resolved package will not be installed automatically

I was able to simply do `apt install systemd-resolved` and everything worked again.

**Comment by tripunto** [comment] 2023-07-09 21:19
>Doesn't seem like systemd-resolved is available in Debian 12?

It seems that version 1.5.0 is only compatible with debian 12, where "YES" you can install systemd-resolved
I tried to install it several times on my raspberry and it didn't work and the one I had only works on localhost... it's impossible to access from another device on my network

I have debian 12 installed on another sd and yes I can install systemd-resolved, but before installing it I want to make a backup... I already downloaded kde plasma 4 times

**Comment by Skynetnexus** [comment] 2023-07-19 22:01
Following the Home Assistant Supervised installation page the I kicked off a new net install installation last night and the internet worked until I started installing the dependencies ( one by one ) , as soon as I installed systemd-resolved the DNS broke. The only way I could continue the installation was by running "sudo systemctl stop systemd-resolved".

For me the issue is systemd-resolved is not playing nicely the Debian 12 or one of the other dependencies ( listed below ).
apt install \
apparmor \
jq \
wget \
curl \
udisks2 \
libglib2.0-bin \
network-manager \
dbus \
lsb-release \
systemd-journal-remote \
systemd-resolved -y

**Comment by Skynetnexus** [comment] 2023-07-23 10:15
@snakuzzo Thank you so much! Your solution has enabled me to complete the installation of home assistant and I now have a working installation after trying many other solutions.  

Unfortunately my internet died again before I could apply my save Home Assistant backup. I am not sure if this was the root cause but I have previously been advised to disable ipv6 inside home assistant ( settings/system/network ) which I did and then to entered the commands below to get the internet going again. The internet is now working, even after multiple reboots.

sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo systemctl enable systemd-resolved.service
sudo systemctl start systemd-resolved.service

**Comment by RichardPar** [comment] 2023-07-26 09:44
Is there a planned fix for this? ... Khadas VIM4 only have a Debian11 avaliable at this point in time.

**Comment by RichardPar** [comment] 2023-07-26 10:10
> Follow [this](https://github.com/home-assistant/supervised-installer/issues/304#issuecomment-1644070922) to bypass the problem. Is not an issue related to HA Supervised installer...it's related to `systemd-resolved` package

```
khadas@Khadas:~$ sudo apt-get install systemd-resolved -y
...
The following packages have unmet dependencies:
 systemd-resolved : Depends: systemd (= 252.5-2~bpo11+1)
                    Recommends: libnss-resolve but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Thanks... systemd-resolved fails completely ... its trying to install version 252 but the system is actually 247

**Comment by snakuzzo** [comment] 2023-07-26 10:16
If you follow guidelines, You have to use last Debian stable release (12)

**Comment by RichardPar** [comment] 2023-07-26 10:28
> If you follow guidelines, You have to use last Debian stable release (12)

Impossible :D as many SBC boards dont have Debian12 .. only Debian11.

**Comment by snakuzzo** [comment] 2023-07-26 10:35
Try [this](https://stackoverflow.com/a/35679746)

**Comment by RichardPar** [comment] 2023-07-26 11:22
> Try [this](https://stackoverflow.com/a/35679746) Anyway, Debian 11 is officially supported just for 4 months from the latest Deban 12 stable release.

This failed... there was a 'Too many errors, failing'  and then aptitude quits

I rolled back the supervised installer to 1.4.3 and continued.

**Comment by Reynold29** [comment] 2023-07-29 10:19
> If you follow guidelines, You have to use last Debian stable release (12)

I'm hella confused. I'm on Debian 11. And it shows no install candidate for systemd. Should I update to Debian 12 and run HA installer to fix this issue?

**Comment by snakuzzo** [comment] 2023-07-29 10:28
HA Supervised is officially supported on latest stable release (Debian 12). So...you need to upgrade to Debian 12 (search on googole, there are a lot of guides) and follow official guidelines to install/upgrade HA Supervised installation. When you will installa systemd-resolved and you will got DNS resolution problem, all you have to do is follow [these steps](https://github.com/home-assistant/supervised-installer/issues/304#issuecomment-1644070922)

**Comment by andygikling** [comment] 2023-08-20 19:34
@snakuzzo  

Your solution does work around the issue.  However, it has shortcomings:

- It does not work for anyone using a subnet other than 192.168.1.1/24 - there might not be a DNS server at 192.168.1.1 for many people.
- One could also set FallbackDNS=8.8.8.8 in /etc/systemd/resolved.conf and then you'd get Google's DNS which should always work but might be slower for some people.
- According to this, supervised-installer should not be dependent on systemd-resolved in Debian 12 (as suggested previously in this thread) https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html#systemd-resolved

A real fix is needed here.  In Debian 12, DNS works correctly out of the box.  Installing systemd-resolved is what's breaking things.  We have two good options to move forward with:

- Make systemd-resolved install correctly on Debian 12.
- When Debian 11 fall out of support here, change supervised-installer to not require the systemd-resolved package.

**Comment by snakuzzo** [comment] 2023-08-20 19:41
I agree...

But about 192.168.1.1, mine was just an example ;)

**Comment by ffries** [comment] 2023-08-29 06:55
I installed Debian 12.1 on a PC Engies APU2 board and I was stopped by this issue until I added DNS server to /etc/systemd/resolved.conf. This is quite a simple bug but it will stop all users if not documented in the main documentation.

**Comment by snakuzzo** [comment] 2023-08-29 07:36
This Is wrong. resolv.conf should not be manually eidted. Read [this](https://github.com/home-assistant/supervised-installer/issues/304#issuecomment-1644070922) and [this](https://github.com/home-assistant/supervised-installer/issues/304#issuecomment-1685373388)

**Comment by snakuzzo** [comment] 2023-08-30 19:44
As I said before...edit resolv.conf is not a best practice

**Closed** 2023-11-07 22:56 UTC
Labels: bug
