### ISSUE TITLE
Bug Report: I can install it。

### ISSUE THREAD

**Issue by stspqxl** [home-assistant/supervised-installer#315] opened 2023-08-15 18:02 UTC
### OS Version

 Debian GNU/Linux 12 (bookworm)

### System Information

Linux N1 5.10.189-ophub #1 SMP PREEMPT Wed Aug 9 05:20:46 EDT 2023 aarch64 GNU/Linux

### What happened?

I can install.

### Machine Type

qemuarm-64

### Installer output

```text
root@N1:~# dpkg -i homeassistant-supervised.deb
(Reading database ... 40534 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
Adding 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Adding 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Adding 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Adding 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.5.0) ...
Setting up homeassistant-supervised (1.5.0) ...
[info] Restarting NetworkManager
[info] Set up systemd-journal-gatewayd socket file
[info] Enable systemd-journal-gatewayd
dpkg: error processing package homeassistant-supervised (--install):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 homeassistant-supervised
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by johny-mnemonic** [comment] 2023-08-16 22:26
Looks like a duplicate of https://github.com/home-assistant/supervised-installer/issues/310 at first glance.

**Comment by reserve85** [comment] 2023-08-17 04:21
thank you, had the same problem. https://github.com/home-assistant/supervised-installer/issues/310#issuecomment-1621740176 helped me a lot! 
systemd-journal-gatewayd.service was inactive and a reinstall and finally starting the service did the trick!

**Closed** 2023-08-17 05:35 UTC
Labels: bug
